# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obsid < Formula
  desc ""
  homepage "https://github.com/DylanSatow/obsid/"
  version "1.0.0"

  on_macos do
    url "https://github.com/DylanSatow/obsid/releases/download/v1.0.0/obsid_1.0.0_darwin_all.tar.gz"
    sha256 "3e7099677fb6fa73c52932bbdad92f9bc6fef39be35742f895f71720eff008c6"

    def install
      bin.install "obsid"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/DylanSatow/obsid/releases/download/v1.0.0/obsid_1.0.0_linux_amd64.tar.gz"
      sha256 "bf0e4a9d8318bc218b7650a2807b4f1ab25ba47f180a68753d009b3783a24567"
      def install
        bin.install "obsid"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/DylanSatow/obsid/releases/download/v1.0.0/obsid_1.0.0_linux_arm64.tar.gz"
      sha256 "47094b3399e4dea892a2c83895a139058422dc18a99cc804e46841a7d0f0078b"
      def install
        bin.install "obsid"
      end
    end
  end
end
